/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#fff8f6',
        'primary-fixed': '#acf4a4',
        'tertiary-fixed': '#cceacd',
        'surface-container': '#ffe9e3',
        'on-primary-fixed': '#002203',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#00731e',
        'surface-tint': '#2a6b2c',
        'primary-container': '#1b5e20',
        'inverse-surface': '#452920',
        'surface-container-high': '#ffe2d9',
        'on-secondary-fixed-variant': '#005313',
        'surface-dim': '#fed0c1',
        'on-background': '#2d150d',
        'surface-variant': '#ffdbcf',
        'on-surface': '#2d150d',
        'on-error': '#ffffff',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'on-tertiary-container': '#b0cdb1',
        'on-tertiary-fixed-variant': '#334d37',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#ffede8',
        'tertiary-fixed-dim': '#b1ceb2',
        'on-primary-fixed-variant': '#0c5216',
        'on-error-container': '#93000a',
        'on-primary-container': '#90d689',
        'tertiary-container': '#3e5842',
        'error': '#ba1a1a',
        'surface-container-highest': '#ffdbcf',
        'tertiary': '#27412c',
        'on-tertiary': '#ffffff',
        'secondary': '#006e1c',
        'on-secondary-fixed': '#002204',
        'surface-container-low': '#fff1ed',
        'primary-fixed-dim': '#91d78a',
        'primary': '#00450d',
        'secondary-fixed': '#94f990',
        'secondary-container': '#91f78e',
        'surface-bright': '#fff8f6',
        'surface': '#fff8f6',
        'outline': '#717a6d',
        'inverse-primary': '#91d78a',
        'on-tertiary-fixed': '#07200e',
        'secondary-fixed-dim': '#78dc77',
        'outline-variant': '#c0c9bb',
        'on-surface-variant': '#41493e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'margin-desktop': '48px',
        'margin-mobile': '16px',
        'stack-sm': '8px',
        'stack-md': '16px',
        gutter: '24px',
        'container-max': '1440px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'headline': ['Montserrat', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
      },
      maxWidth: {
        'container': '1440px',
      },
    },
  },
  plugins: [],
};
